import React, { createContext, useContext, useState } from 'react'
import translateText from '@/api/translate'
import type { TranslationResult } from '@/api/translate'

type Locale = 'en' | 'pt' | 'es'

type LangContextType = {
  locale: Locale
  setLocale: (l: Locale) => void
  t: (key: string) => string
  translateUI: (key: string) => string
}

const translations: Record<Locale, Record<string, string>> = {
  en: {
    login: 'Login',
    enter: 'Enter',
    searchPlaceholder: 'Search recipes...',
    featured: 'Featured recipes',
    back: 'Back',
    servings: 'Servings',
    readyIn: 'Ready in',
    minutes: 'min',
    ingredients: 'Ingredients',
    instructions: 'Instructions',
    invalidId: 'Invalid ID.',
    loadError: 'Error loading recipe',
    searchError: 'Error searching recipes',
    invalidQuery: 'Invalid query.',
    noRecipesFound: 'No recipes found.',
    results: 'Results for',
    details: 'View details',
    about: 'About: Papo de Panela is a recipe repository.',
    contact: 'Contact: contato@papodepanela.local',
    language: 'Language',
    portuguese: 'Português',
    english: 'English',
    spanish: 'Español',
    randomRecipes: 'Featured recipes',
    randomRecipesDesc: 'Randomly selected recipes from our repository.',
    searching: 'Searching...',
    searchingFor: 'Searching for',
    translationFailed: 'Could not translate the term; searching with the original term.',
    recipes: 'Recipes',
    favorites: 'Favorites',
    categories: 'Categories',
    aboutMenu: 'About',
    cancel: 'Cancel',
    logout: 'Logout',
    'home.subtitle': 'Discover, create and share delicious recipes from around the world',
    'community.title': 'Community Recipes',
    'community.subtitle': 'Discover recipes created by our community',
    'community.description': 'Discover and share recipes created by food lovers from around the world',
    'community.noRecipes': 'No recipes yet',
    'community.createFirst': 'Be the first to share a recipe',
    'community.createRecipe': 'Create Recipe',
    'community.by': 'by',
    'community.createdBy': 'Created by',
    'community.loadError': 'Error loading recipes',
    'community.recipeNotFound': 'Recipe not found',
    'createRecipe.title': 'Create Recipe',
    'createRecipe.subtitle': 'Share your favorite recipe with the community',
    'createRecipe.description': 'Create and share your own recipes with the community',
    'createRecipe.titleField': 'Title',
    'createRecipe.titlePlaceholder': 'My delicious recipe...',
    'createRecipe.descriptionField': 'Description',
    'createRecipe.descriptionPlaceholder': 'A brief description of the recipe...',
    'createRecipe.prepTime': 'Prep Time',
    'createRecipe.servingsField': 'Servings',
    'createRecipe.category': 'Category',
    'createRecipe.categoryPlaceholder': 'Dessert, Main Course, etc.',
    'createRecipe.cuisine': 'Cuisine',
    'createRecipe.cuisinePlaceholder': 'Italian, Brazilian, etc.',
    'createRecipe.imageUrl': 'Image URL (optional)',
    'createRecipe.ingredientsField': 'Ingredients',
    'createRecipe.ingredientsPlaceholder': '1 cup flour\n2 eggs\n1/2 cup sugar',
    'createRecipe.instructionsField': 'Instructions',
    'createRecipe.instructionsPlaceholder': 'Preheat oven to 180°C\nMix ingredients\nBake for 30 minutes',
    'createRecipe.onePerLine': 'one per line',
    'createRecipe.fillRequired': 'Please fill all required fields',
    'createRecipe.error': 'Error creating recipe',
    'createRecipe.creating': 'Creating...',
    'createRecipe.createButton': 'Create Recipe',
    'createRecipe.callToActionTitle': '👨‍🍳 Share your recipes!',
    'createRecipe.callToActionDesc': 'Have a special recipe? Share it with the community and inspire other cooks!',
    'community.browseRecipes': 'Browse Recipes',
    'aiRecipe.title': 'Generate Recipe with AI',
    'aiRecipe.subtitle': 'Enter the ingredients you have and let AI create a delicious recipe for you!',
    'aiRecipe.description': 'Use artificial intelligence to create personalized recipes with your favorite ingredients',
    'aiRecipe.ingredientsField': 'Ingredients',
    'aiRecipe.ingredientsPlaceholder': 'e.g., chicken, tomato, onion, garlic (comma separated)',
    'aiRecipe.ingredientsRequired': 'Please provide at least one ingredient',
    'aiRecipe.cuisineField': 'Cuisine Type',
    'aiRecipe.cuisinePlaceholder': 'e.g., Italian, Mexican, Brazilian',
    'aiRecipe.mealTypeField': 'Meal Type',
    'aiRecipe.mealTypePlaceholder': 'e.g., Breakfast, Lunch, Dinner',
    'aiRecipe.dietaryField': 'Dietary Restrictions',
    'aiRecipe.dietaryPlaceholder': 'e.g., Vegetarian, Gluten-free, Vegan',
    'aiRecipe.servingsField': 'Servings',
    'aiRecipe.generating': 'Generating recipe...',
    'aiRecipe.generateButton': 'Generate Recipe with AI',
    'aiRecipe.error': 'Error generating recipe. Please try again.',
    'aiRecipe.success': 'Recipe generated successfully!',
    'aiRecipe.generateAnother': 'Generate Another Recipe',
    'backToHome': 'Back to Home',
    'tips': 'Tips',
  },
  pt: {
    login: 'Entrar',
    enter: 'Entrar',
    searchPlaceholder: 'Pesquisar receitas...',
    featured: 'Receitas em destaque',
    back: 'Voltar',
    servings: 'Porções',
    readyIn: 'Pronto em',
    minutes: 'min',
    ingredients: 'Ingredientes',
    instructions: 'Modo de preparo',
    invalidId: 'ID inválido.',
    loadError: 'Erro ao carregar receita',
    searchError: 'Erro ao buscar receitas',
    invalidQuery: 'Query inválida.',
    noRecipesFound: 'Nenhuma receita encontrada.',
    results: 'Resultados para',
    details: 'Ver detalhes',
    about: 'Sobre: Papo de Panela é um repositório de receitas.',
    contact: 'Contato: contato@papodepanela.local',
    language: 'Idioma',
    portuguese: 'Português',
    english: 'English',
    spanish: 'Español',
    randomRecipes: 'Receitas em destaque',
    randomRecipesDesc: 'Receitas selecionadas aleatoriamente do nosso repositório.',
    searching: 'Buscando...',
    searchingFor: 'Buscando por',
    translationFailed: 'Não foi possível traduzir o termo; buscando com o termo original.',
    recipes: 'Receitas',
    favorites: 'Favoritos',
    categories: 'Categorias',
    aboutMenu: 'Sobre',
    cancel: 'Cancelar',
    logout: 'Sair',
    'home.subtitle': 'Descubra, crie e compartilhe receitas deliciosas de todo o mundo',
    'community.title': 'Receitas da Comunidade',
    'community.subtitle': 'Descubra receitas criadas pela nossa comunidade',
    'community.description': 'Descubra e compartilhe receitas criadas por amantes da culinária de todo o mundo',
    'community.noRecipes': 'Ainda não há receitas',
    'community.createFirst': 'Seja o primeiro a compartilhar uma receita',
    'community.createRecipe': 'Criar Receita',
    'community.by': 'por',
    'community.createdBy': 'Criada por',
    'community.loadError': 'Erro ao carregar receitas',
    'community.recipeNotFound': 'Receita não encontrada',
    'createRecipe.title': 'Criar Receita',
    'createRecipe.subtitle': 'Compartilhe sua receita favorita com a comunidade',
    'createRecipe.description': 'Crie e compartilhe suas próprias receitas com a comunidade',
    'createRecipe.titleField': 'Título',
    'createRecipe.titlePlaceholder': 'Minha receita deliciosa...',
    'createRecipe.descriptionField': 'Descrição',
    'createRecipe.descriptionPlaceholder': 'Uma breve descrição da receita...',
    'createRecipe.prepTime': 'Tempo de Preparo',
    'createRecipe.servingsField': 'Porções',
    'createRecipe.category': 'Categoria',
    'createRecipe.categoryPlaceholder': 'Sobremesa, Prato Principal, etc.',
    'createRecipe.cuisine': 'Culinária',
    'createRecipe.cuisinePlaceholder': 'Italiana, Brasileira, etc.',
    'createRecipe.imageUrl': 'URL da Imagem (opcional)',
    'createRecipe.ingredientsField': 'Ingredientes',
    'createRecipe.ingredientsPlaceholder': '1 xícara de farinha\n2 ovos\n1/2 xícara de açúcar',
    'createRecipe.instructionsField': 'Modo de Preparo',
    'createRecipe.instructionsPlaceholder': 'Pré-aqueça o forno a 180°C\nMisture os ingredientes\nAsse por 30 minutos',
    'createRecipe.onePerLine': 'um por linha',
    'createRecipe.fillRequired': 'Por favor, preencha todos os campos obrigatórios',
    'createRecipe.error': 'Erro ao criar receita',
    'createRecipe.creating': 'Criando...',
    'createRecipe.createButton': 'Criar Receita',
    'createRecipe.callToActionTitle': '👨‍🍳 Compartilhe suas receitas!',
    'createRecipe.callToActionDesc': 'Tem uma receita especial? Compartilhe com a comunidade e inspire outros cozinheiros!',
    'community.browseRecipes': 'Ver Receitas',
    'aiRecipe.title': 'Gerar Receita com IA',
    'aiRecipe.subtitle': 'Informe os ingredientes que você tem e deixe a IA criar uma receita deliciosa para você!',
    'aiRecipe.description': 'Use inteligência artificial para criar receitas personalizadas com seus ingredientes favoritos',
    'aiRecipe.ingredientsField': 'Ingredientes',
    'aiRecipe.ingredientsPlaceholder': 'Ex: frango, tomate, cebola, alho (separados por vírgula)',
    'aiRecipe.ingredientsRequired': 'Por favor, informe pelo menos um ingrediente',
    'aiRecipe.cuisineField': 'Tipo de Culinária',
    'aiRecipe.cuisinePlaceholder': 'Ex: Italiana, Mexicana, Brasileira',
    'aiRecipe.mealTypeField': 'Tipo de Refeição',
    'aiRecipe.mealTypePlaceholder': 'Ex: Café da manhã, Almoço, Jantar',
    'aiRecipe.dietaryField': 'Restrições Alimentares',
    'aiRecipe.dietaryPlaceholder': 'Ex: Vegetariano, Sem glúten, Vegano',
    'aiRecipe.servingsField': 'Porções',
    'aiRecipe.generating': 'Gerando receita...',
    'aiRecipe.generateButton': 'Gerar Receita com IA',
    'aiRecipe.error': 'Erro ao gerar receita. Tente novamente.',
    'aiRecipe.success': 'Receita gerada com sucesso!',
    'aiRecipe.generateAnother': 'Gerar Outra Receita',
    'backToHome': 'Voltar ao Início',
    'tips': 'Dicas',
  },
  es: {
    login: 'Iniciar sesión',
    enter: 'Entrar',
    searchPlaceholder: 'Buscar recetas...',
    featured: 'Recetas destacadas',
    back: 'Volver',
    servings: 'Porciones',
    readyIn: 'Listo en',
    minutes: 'min',
    ingredients: 'Ingredientes',
    instructions: 'Instrucciones',
    invalidId: 'ID inválido.',
    loadError: 'Error al cargar la receta',
    searchError: 'Error al buscar recetas',
    invalidQuery: 'Consulta inválida.',
    noRecipesFound: 'No se encontraron recetas.',
    results: 'Resultados para',
    details: 'Ver detalles',
    about: 'Acerca de: Papo de Panela es un repositorio de recetas.',
    contact: 'Contacto: contato@papodepanela.local',
    language: 'Idioma',
    portuguese: 'Português',
    english: 'English',
    spanish: 'Español',
    randomRecipes: 'Recetas destacadas',
    randomRecipesDesc: 'Recetas seleccionadas al azar de nuestro repositorio.',
    searching: 'Buscando...',
    searchingFor: 'Buscando por',
    translationFailed: 'No se pudo traducir el término; buscando con el término original.',
    recipes: 'Recetas',
    favorites: 'Favoritos',
    categories: 'Categorías',
    aboutMenu: 'Acerca de',
    cancel: 'Cancelar',
    logout: 'Cerrar sesión',
    'home.subtitle': 'Descubre, crea y comparte recetas deliciosas de todo el mundo',
    'community.title': 'Recetas de la Comunidad',
    'community.subtitle': 'Descubre recetas creadas por nuestra comunidad',
    'community.description': 'Descubre y comparte recetas creadas por amantes de la cocina de todo el mundo',
    'community.noRecipes': 'Aún no hay recetas',
    'community.createFirst': 'Sé el primero en compartir una receta',
    'community.createRecipe': 'Crear Receta',
    'community.by': 'por',
    'community.createdBy': 'Creada por',
    'community.loadError': 'Error al cargar recetas',
    'community.recipeNotFound': 'Receta no encontrada',
    'createRecipe.title': 'Crear Receta',
    'createRecipe.subtitle': 'Comparte tu receta favorita con la comunidad',
    'createRecipe.description': 'Crea y comparte tus propias recetas con la comunidad',
    'createRecipe.titleField': 'Título',
    'createRecipe.titlePlaceholder': 'Mi receta deliciosa...',
    'createRecipe.descriptionField': 'Descripción',
    'createRecipe.descriptionPlaceholder': 'Una breve descripción de la receta...',
    'createRecipe.prepTime': 'Tiempo de Preparación',
    'createRecipe.servingsField': 'Porciones',
    'createRecipe.category': 'Categoría',
    'createRecipe.categoryPlaceholder': 'Postre, Plato Principal, etc.',
    'createRecipe.cuisine': 'Cocina',
    'createRecipe.cuisinePlaceholder': 'Italiana, Brasileña, etc.',
    'createRecipe.imageUrl': 'URL de Imagen (opcional)',
    'createRecipe.ingredientsField': 'Ingredientes',
    'createRecipe.ingredientsPlaceholder': '1 taza de harina\n2 huevos\n1/2 taza de azúcar',
    'createRecipe.instructionsField': 'Instrucciones',
    'createRecipe.instructionsPlaceholder': 'Precalienta el horno a 180°C\nMezcla los ingredientes\nHornea por 30 minutos',
    'createRecipe.onePerLine': 'uno por línea',
    'createRecipe.fillRequired': 'Por favor, completa todos los campos obligatorios',
    'createRecipe.error': 'Error al crear receta',
    'createRecipe.creating': 'Creando...',
    'createRecipe.createButton': 'Crear Receta',
    'createRecipe.callToActionTitle': '👨‍🍳 ¡Comparte tus recetas!',
    'createRecipe.callToActionDesc': '¿Tienes una receta especial? ¡Compártela con la comunidad e inspira a otros cocineros!',
    'community.browseRecipes': 'Ver Recetas',
    'aiRecipe.title': 'Generar Receta con IA',
    'aiRecipe.subtitle': '¡Ingresa los ingredientes que tienes y deja que la IA cree una receta deliciosa para ti!',
    'aiRecipe.description': 'Usa inteligencia artificial para crear recetas personalizadas con tus ingredientes favoritos',
    'aiRecipe.ingredientsField': 'Ingredientes',
    'aiRecipe.ingredientsPlaceholder': 'Ej: pollo, tomate, cebolla, ajo (separados por coma)',
    'aiRecipe.ingredientsRequired': 'Por favor, proporciona al menos un ingrediente',
    'aiRecipe.cuisineField': 'Tipo de Cocina',
    'aiRecipe.cuisinePlaceholder': 'Ej: Italiana, Mexicana, Brasileña',
    'aiRecipe.mealTypeField': 'Tipo de Comida',
    'aiRecipe.mealTypePlaceholder': 'Ej: Desayuno, Almuerzo, Cena',
    'aiRecipe.dietaryField': 'Restricciones Dietéticas',
    'aiRecipe.dietaryPlaceholder': 'Ej: Vegetariano, Sin gluten, Vegano',
    'aiRecipe.servingsField': 'Porciones',
    'aiRecipe.generating': 'Generando receta...',
    'aiRecipe.generateButton': 'Generar Receta con IA',
    'aiRecipe.error': 'Error al generar receta. Inténtalo de nuevo.',
    'aiRecipe.success': '¡Receta generada con éxito!',
    'aiRecipe.generateAnother': 'Generar Otra Receta',
    'backToHome': 'Volver al Inicio',
    'tips': 'Consejos',
  },
}

const LangContext = createContext<LangContextType | undefined>(undefined)

export const LanguageProvider: React.FC<React.PropsWithChildren<{}>> = ({ children }) => {
  const [locale, setLocale] = useState<Locale>('pt')

  const t = (key: string) => translations[locale]?.[key] ?? key

  const value: LangContextType = {
    locale,
    setLocale: (l: Locale) => setLocale(l),
    t,
    translateUI: t,
  }

  return <LangContext.Provider value={value}>{children}</LangContext.Provider>
}

export function useLanguage() {
  const ctx = useContext(LangContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}

export async function translateForLocale(text: string, target: Locale) {
  if (!text) return text
  if (target === 'en') return text
  try {
    const res: TranslationResult = await translateText(text, target, 'auto')
    return res.text
  } catch (e) {
    return text
  }
}

export type { Locale }
